### ISSUE TITLE
Creating mono layout support

### ISSUE THREAD

**Issue by Rynaro** [Rynaro/estratto#2]
Estratto was builted with intent to deal with multi-layout as primary context, but one of most common layout type of fixed width.

In mono layout type generally has header, and footer, that these lines do not shares the same pattern of principal content lines.

Suggested initial point of this feature:

```yaml
layout:
  name: 'monolayout'
  multi-register: false # or nonexistent key
  header: true
  footer: true
  registers:
    - header:
     # content
    - register:
     # content
    - footer:
     # content
```
